from sqlalchemy import Column, String, Integer, DateTime, ForeignKey, Text, Boolean
from sqlalchemy.sql import func
from database import Base


class DocumentHint(Base):
    """AI-generated hints, tips, and reminders based on document content"""
    __tablename__ = "document_hints"

    id = Column(Integer, primary_key=True, index=True)
    document_id = Column(Integer, ForeignKey("documents.id"), nullable=False, index=True)
    
    # Type of hint
    hint_type = Column(String(50), nullable=False)  # "expiration", "renewal", "review_needed", "action_required"
    
    # Content
    content = Column(Text, nullable=False)  # e.g., "This contract expires Q3 2025"
    
    # AI metadata
    ai_suggested = Column(Boolean, default=True)  # Was this auto-generated by AI?
    ai_model_used = Column(String, nullable=True)  # Which model generated this hint
    confidence_score = Column(Integer, nullable=True)  # 0-100, how confident is the AI?
    
    # User interaction
    acknowledged_by = Column(Integer, ForeignKey("users.id"), nullable=True)
    acknowledged_at = Column(DateTime(timezone=True), nullable=True)
    
    dismissed = Column(Boolean, default=False)
    dismissed_at = Column(DateTime(timezone=True), nullable=True)
    
    # Timestamps
    created_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False, index=True)
